# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='Titre', max_length=200),
        ),
    ]
