# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='votes',
        ),
    ]
